###################################################
# DAN 1.28 8pm: started this file tonight
#   MY FIRST GHA WORKFLOW!
#
# ref doc: https://docs.github.com/en/actions/about-github-actions/understanding-github-actions
#
###################################################

name: basic workflow dispatchio thingo

on: workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "we did sumpin i guest it"


 
# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: my-step
#         run: echo "Hello Danno Feb 1 - dwc"
