###################################################
# DAN 2.2 Setting up automatic deploy when pushing code
####### #####   ############  ##################
#
# ref doc: https://docs.github.com/en/actions/about-github-actions/understanding-github-actions
# DANHERE 2.2 930pm: the 'deploy' command below works, now need to try 'build' then docker to ECR
###################################################


###################################################
name: 4 Pull Autmation

on: 
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "4 Insert duh POOL otter-mation to run when pulling the Github repo in the ${{ github.event.inputs.environment }} environment (code sdfasd332 )"

