###################################################
# DANHERE 2.2 730pm: working on 2nd GHA action
####### #####   ############  ##################
####### #####   ############  ##################
#
# ref doc: https://docs.github.com/en/actions/about-github-actions/understanding-github-actions
#
###################################################


###################################################
name: 3 Multiple Jobs

on: 
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Environment to deploy to::'
        required: true
        type: environment
      notify: 
        description: 'Send email confirmation?'
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "dwc Deploying to ${{ github.event.inputs.environment }} environment (code 57w3vv )"

  notify:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.notify }} # DAN 2.3:534pm: this conditional does not seem to work - it always runs
    steps:
      - run: echo "** Email notification was indeed sent to users"
#    if: ! ${{ github.event.inputs.notify }}
#    steps:
#      - run: echo "!!! Email notification WAS NOT sent to users"    




 
# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: my-step
#         run: echo "Hello Danno Feb 1 - dwc"
