###################################################
# DANHERE 2.2 730pm: working on 2nd GHA action
####### #####   ############  ##################
#
# ref doc: https://docs.github.com/en/actions/about-github-actions/understanding-github-actions
#
###################################################


###################################################
name: 4 Push and Pull

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "gettin buildidd diss to ${{ github.event.inputs.environment }} environment (code sdfasd332 )"

