###################################################
# DANHERE 2.2 730pm: working on 2nd GHA action
####### #####   ############  ##################
####### #####   ############  ##################
#
# ref doc: https://docs.github.com/en/actions/about-github-actions/understanding-github-actions
#
###################################################


###################################################
name: 2 Inputs - Environments

on: 
  workflow_dispatch:
    inputs:
      environment: 
        description: 'Env to deploy to (x80272)'
        required: true
        type: environment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "dwc Deploying to ${{ github.event.inputs.environment }} environment (code 57w3vv )"




 
# jobs:
#   my-job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: my-step
#         run: echo "Hello Danno Feb 1 - dwc"
